WITH EMP_MAN AS ( SELECT T1.ID, T1.NAME, T1.SALARY, T2.NAME AS MANAGER, T2.SALARY AS MANAGER_SALARY FROM EMPLOYEE AS T1
LEFT JOIN EMPLOYEE AS T2
ON T1.MANAGERID = T2.ID)
SELECT NAME AS Employee FROM EMP_MAN 
WHERE SALARY> MANAGER_SALARY;